name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Dependencies
        run: flutter pub get

      # Create a Podfile if it doesn't exist
      - name: Create Podfile if not exists
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "Creating Podfile..."
            cd ios
            pod init
            echo "platform :ios, '12.0'\ntarget 'Runner' do\n  use_frameworks!\n  use_modular_headers!\nend" > Podfile
          fi

      # Only run pod repo update if Podfile exists
      - name: Update CocoaPods Repo
        if: steps.createPodfile.outputs.exists == 'true'
        run: pod repo update
        working-directory: ios

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Prepare IPA Structure
        run: mkdir Payload && mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
